CREATE TABLE testquestion (
	testquestion_id INTEGER NOT NULL,
	testquestion_text VARCHAR(300) NOT NULL,
	test_id INTEGER NOT NULL,
	CONSTRAINT testquestion_pk PRIMARY KEY (testquestion_id)
);
CREATE SEQUENCE testquestion_id_gen INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE;

CREATE TABLE test (
	test_id INTEGER NOT NULL,
	test_name VARCHAR(100) NOT NULL,
	test_desc VARCHAR(300) NULL,
	CONSTRAINT test_pk PRIMARY KEY (test_id)
);
CREATE SEQUENCE test_id_gen INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE;