CREATE TABLE answer (
	answer_id INTEGER NOT NULL,
	answer_text VARCHAR(200) NOT NULL,
	answer_right INTEGER NOT NULL,
	testquestion_id INTEGER NOT NULL,
	CONSTRAINT answer_pk PRIMARY KEY (answer_id)
);
CREATE SEQUENCE answer_id_gen INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE;