@startuml
rectangle "Личный кабинет"{
    rectangle "Родитель"{
        (Курсы)
        (Личная информация)
        (Ребенок)
        (Курсы)-->(Список курсов)
        (Список курсов)-->(Запись на курс)
        (Ребенок)-->(Пройденные курсы)
        (Ребенок)-->(Проходимые курсы)
        (Пройденные курсы)-->(Достижения)
        (Проходимые курсы)-->(Посещаемость)
        (Проходимые курсы)-->(Успеваемость)
    }
    rectangle "Учащийся"{
        (Курсы.)
        (Личная информация.)
        (Тест)
        (Курсы.)-->(Пройденные)
        (Курсы.)-->(Проходимые)
        (Курсы.)-->(Доступные)
        (Пройденные)-->(Достижения.)
        (Пройденные)-->(Материалы)
        (Проходимые)-->(Материалы)
        (Проходимые)-->(Расписание)
        (Проходимые)-->(Вход в курс)
    }
    rectangle "Преподаватель"{
        (Личная информация )
        (Курсы )-->(Повышение квалификации)
        (Курсы )-->(Заявки)
        (Курсы )-->(Управление курсами)
        (Управление курсами)-->(Группы)
        (Управление курсами)-->(Отчетные материалы)
        (Заявки)-->(Создание)
        (Заявки)-->(Удаление)
        (Заявки)-->(Редактирование)
        (Повышение квалификации)-->(Пройденные )
        (Повышение квалификации)-->(Проходимые )
        (Повышение квалификации)-->(Запись )
        (Проходимые )-->(Материалы )
        (Проходимые )-->(Вход в курс )
        (Пройденные )-->(Материалы )
        (Пройденные )-->(Достижения )
    }
    rectangle "Системный администратор"{
        (Пользователи)-->(Добавить)
        (Пользователи)-->(Удалить)
        (Пользователи)-->(Редактировать)
        (Роли)-->(Добавить )
        (Роли)-->(Удалить )
        (Роли)-->(Редактировать )
        (Права)-->( Добавить)
        (Права)-->( Удалить)
        (Права)-->( Редактировать)
        (Удаление )
    }
    rectangle "Методист"{
        (Программы)-->(удаление)
        (Программы)-->(создание)
        (Программы)-->(редактирование)
        (Программы)-->(настройка прав)
        (Документы)-->(удаление )
        (Документы)-->(создание )
        (Документы)-->(редактирование )
        (Мероприятия)-->( удаление)
        (Мероприятия)-->( создание)
        (Мероприятия)-->( редактирование)
        (Учащиеся)-->(удаление.)
        (Учащиеся)-->(создание.)
        (Учащиеся)-->(редактирование.)
    }
    rectangle "Администратор активности"{
        (Посещаемость )-->(Заполнение)
        (Новости)-->(Добавить.)
        (Новости)-->(Удалить.)
        (Новости)-->(Редактировать.)
        (Отчетность )-->(Вывести посещаемость)
    }
    rectangle "Директор"{
        (Отчетность)
        (Отчетность)-->(Сформировать отчетность об учащихся)
        (Отчетность)-->(Сформировать отчетность о группах)
        (Группы )-->(Распределить учащихся)
    }
}
@enduml