@startuml
:Пользователь: as user
rectangle "Дом научной коллаборации им. А. А. Фридмана"{
    rectangle "Личный кабинет"{
        rectangle "Родитель"{
            (Курсы)
            (Личная информация)
            (Ребенок)
            (Курсы)-->(Список курсов)
            (Список курсов)-->(Запись на курс)
            (Ребенок)-->(Пройденные курсы)
            (Ребенок)-->(Проходимые курсы)
            (Пройденные курсы)-->(Достижения)
            (Проходимые курсы)-->(Посещаемость)
            (Проходимые курсы)-->(Успеваемость)
        }
        rectangle "Учащийся"{
            (Курсы.)
            (Личная информация.)
            (Тест)
            (Курсы.)-->(Пройденные)
            (Курсы.)-->(Проходимые)
            (Курсы.)-->(Доступные)
            (Пройденные)-->(Достижения.)
            (Пройденные)-->(Материалы)
            (Проходимые)-->(Материалы)
            (Проходимые)-->(Расписание)
            (Проходимые)-->(Вход в курс)
        }
        rectangle "Преподаватель"{
            (Личная информация )
            (Курсы )-->(Повышение квалификации)
            (Курсы )-->(Заявки)
            (Курсы )-->(Управление курсами)
            (Управление курсами)-->(Группы)
            (Управление курсами)-->(Отчетные материалы)
            (Заявки)-->(Создание)
            (Заявки)-->(Удаление)
            (Заявки)-->(Редактирование)
            (Повышение квалификации)-->(Пройденные )
            (Повышение квалификации)-->(Проходимые )
            (Повышение квалификации)-->(Запись )
            (Проходимые )-->(Материалы )
            (Пройденные )-->(Материалы )
            (Пройденные )-->(Достижения )
        }
        rectangle "Системный администратор"{
        }
        rectangle "Методист"{
        }
        rectangle "Администратор активности"{
        }
        rectangle "Директор"{
        }
    }
    rectangle "Партнёры. Программы повышения квалификации"{
        (Личный кабинет )
        (Повышение квалификации )
    }
    rectangle "Безопасность, взаимодействие с неавторизованным пользователем"{
        user-->(Авторизация)
        (Авторизация)->(Проверка данных для входа)
    }
    rectangle "Программы обучения"{
        (5)->(6)
    }
}
@enduml