@startuml
:Пользователь: as user
rectangle "Дом научной коллаборации им. А. А. Фридмана"{
    rectangle "Личный кабинет"{
        rectangle "Родитель"{
            (Личная информация)
            (Ребенок)
            (Программы обучения )-->(Список Программ обучения)
            (Список Программ обучения)-->(Запись на программу обучения)
            (Ребенок)-->(Пройденные программы обучения)
            (Ребенок)-->(Проходимые программы обучения)
            (Пройденные программы обучения)-->(Достижения)
            (Проходимые программы обучения)-->(Посещаемость)
            (Проходимые программы обучения)-->(Успеваемость)
        }
        rectangle "Учащийся"{
            (Личная информация.)
            (Тест)
            (Программы обучения.)-->(Пройденные)
            (Программы обучения.)-->(Проходимые)
            (Программы обучения.)-->(Доступные)
            (Пройденные)-->(Достижения.)
            (Пройденные)-->(Материалы)
            (Проходимые)-->(Материалы)
            (Проходимые)-->(Расписание)
            (Проходимые)-->(Вход в программу обучения)
        }
        rectangle "Преподаватель"{
            (Личная информация )
            (Программы  обучения)-->(Повышение квалификации)
            (Программы  обучения)-->(Заявки)
            (Программы  обучения)-->(Управление программами обучения)
            (Управление программами обучения)-->(Группы)
            (Управление программами обучения)-->(Отчетные материалы)
            (Заявки)-->(Создание)
            (Заявки)-->(Удаление)
            (Заявки)-->(Редактирование)
            (Повышение квалификации)-->(Пройденные )
            (Повышение квалификации)-->(Проходимые )
            (Повышение квалификации)-->(Запись )
            (Проходимые )-->(Материалы )
            (Проходимые )-->(Вход в курс )
            (Пройденные )-->(Материалы )
            (Пройденные )-->(Достижения )
        }
        rectangle "Системный администратор"{
            (Пользователи)-->(Добавить)
            (Пользователи)-->(Удалить)
            (Пользователи)-->(Редактировать)
            (Роли)-->(Добавить )
            (Роли)-->(Удалить )
            (Роли)-->(Редактировать )
            (Права)-->( Добавить)
            (Права)-->( Удалить)
            (Права)-->( Редактировать)
            (Удаление )
        }
        rectangle "Работник с контингентом"{
            (Группы )-->(Распределить учащихся)
            (Посещаемость )-->(Заполнение)
            (Отчетность )-->(Вывести посещаемость)
        }
        rectangle "Методист"{
            (Программы)-->(удаление)
            (Программы)-->(создание)
            (Программы)-->(редактирование)
            (Программы)-->(настройка прав)
            (Документы)-->(удаление )
            (Документы)-->(создание )
            (Документы)-->(редактирование )
            (Мероприятия)-->( удаление)
            (Мероприятия)-->( создание)
            (Мероприятия)-->( редактирование)
            (Учащиеся)-->(удаление.)
            (Учащиеся)-->(создание.)
            (Учащиеся)-->(редактирование.)
        }
        rectangle "Администратор активности"{
            (Новости)-->(Добавить.)
            (Новости)-->(Удалить.)
            (Новости)-->(Редактировать.)
        }
        rectangle "Директор"{
            (Отчетность)
            (Отчетность)-->(Сформировать отчетность об учащихся)
            (Отчетность)-->(Сформировать отчетность о группах)
        }
    }
    rectangle "Партнёры. Программы повышения квалификации"{
        (Личный кабинет )
        (Повышение квалификации )
    }
    rectangle "Безопасность, взаимодействие с неавторизованным пользователем"{
        user-->(Авторизация)
        (Авторизация)->(Проверка данных для входа)
        (Проверка данных для входа)-->(Переход в ЛК)
    }
    rectangle "Программы обучения"{
        (5)->(6)
    }
}
@enduml