@startuml
partition "Клиентская часть"{
    (*)-->[Выбор действия]"Отрисовка формы"
    "Обработка ответа сервера"-->"Отрисовка формы"
}
partition "Серверная часть"{
    "Логи приложения"-->[JDBC]"База данных NOSQL"
    partition "Сервер backend"{
        "UNIT-тесты"-->"Контроллер"
        "RowMapper"-->[View]"Сервис"
        "Фильтр запросов"-->"Контроллер"
        -->[Запрос на получение данных]"Сервис"
        -->[Результат работы]"Логи приложения"
        "Сервис"-->[Запрос к бд]"Репозиторий"
        "RowMapper"-->[Сущность]"Репозиторий"
        -->[Результат работы]"Логи приложения"
        "Репозиторий"-->[Проверка данных]"Валидация данных"
        -->[Результат работы]"Логи приложения"
        "Репозиторий"-->[Модель]"Сервис"
        "Сервис"-->[View]"Контроллер"
        "Контроллер"-->[Ответ сервера]"Обработка ответа сервера"
    }
    "Валидация данных"-->[JDBC]"База данных"
    "База данных"-->"RowMapper"
    "Отрисовка формы" -->[POST-запрос] "Фильтр запросов"
}

@enduml